# Generated by Django 5.2.17 on 2026-10-01 10:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('fund', 'TEFAS fund'), ('metal', 'Precious metal'), ('benchmark', 'Benchmark')], max_length=12)),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3)),
                ('unit', models.CharField(default='units', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=12)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], max_length=3)),
                ('date', models.DateField()),
                ('try_per_unit', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('dataset', models.CharField(choices=[('demo', 'Demonstration'), ('live', 'Market data')], max_length=4)),
                ('source', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'date', 'dataset'), name='unique_fx_rate')],
            },
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('demo', 'Demonstration'), ('live', 'Market data')], max_length=4)),
                ('model_name', models.CharField(max_length=120)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('data_end', models.DateField()),
                ('prediction', models.FloatField()),
                ('metrics', models.JSONField(default=dict)),
                ('artifact', models.CharField(max_length=250)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.asset')),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('source', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('dataset', models.CharField(choices=[('demo', 'Demonstration'), ('live', 'Market data')], max_length=4)),
                ('kind', models.CharField(choices=[('news', 'News'), ('social', 'Social')], max_length=8)),
                ('sentiment', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-published_at'],
                'constraints': [models.UniqueConstraint(fields=('external_id', 'dataset', 'kind'), name='unique_news_item')],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('dataset', models.CharField(choices=[('demo', 'Demonstration'), ('live', 'Market data')], default='live', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=10000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=8)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=8, default=1, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='TRY', max_length=3)),
                ('fee', models.DecimalField(decimal_places=4, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('fx_to_try', models.DecimalField(decimal_places=8, default=1, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('memo', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=8, max_digits=22, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('dataset', models.CharField(choices=[('demo', 'Demonstration'), ('live', 'Market data')], max_length=4)),
                ('source', models.CharField(max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.asset')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['dataset', 'date'], name='portfolio_p_dataset_d6115b_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'date', 'dataset'), name='unique_asset_price')],
            },
        ),
    ]
